version: '3'
services:
  bookmeter_web:
    image: 15.3.0-alpine3.10
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
      args:
        NODE_ENV: production
        APP_ENV: production

    command: yarn run start

    ports:
      - '3000:3000'

    volumes:
      - /web
      - ~/.ssl/bookmeter.org:/web/ssl

    depends_on:
      - redis

    environment:
      - NODE_ENV=production
      - APP_ENV=production
      - APP_PORT=3000
      - APP_LISTEN_ADDRESS=0.0.0.0
      - HTTPS_KEY_PATH=/web/ssl/lvh.me.key
      - HTTPS_CERT_PATH=/web/ssl/lvh.me.cert

  redis:
    image: 'redis:alpine'
