name: CI Deploy

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - uses: miloserdow/capistrano-deploy@master
      with:
        target: production
        enc_rsa_key_pth: config/keys/deploy_id_rsa_enc
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
      env:
        SENTRY_LOG_LEVEL: info
        SENTRY_ORG: upolujksiazkepl
        SENTRY_PROJECT: upolujksiazkepl
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
