name: CI

on:
  push:
    branches: [ feature/new-server ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: https://registry.upolujksiazke.pl

      - name: Copy job file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_CI_USER }}
          key: ${{ secrets.SERVER_CI_USER_KEY }}
          port: 22
          source: jobs/site.hcl
          target: /var/www/jobs/upolujksiazke/

      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: registry.upolujksiazke.pl/upolujksiazke-front:latest

      - name: Apply job
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_CI_USER }}
          key: ${{ secrets.SERVER_CI_USER_KEY }}
          port: 22
          script: |
            nomad job run \
              -address=https://localhost:4646 \
              -ca-path=/var/www/nomad/tls/nomad-ca.pem \
              -client-cert=/var/www/nomad/tls/server.pem \
              -client-key=/var/www/nomad/tls/server-key.pem \
              -token=$(cat /var/www/nomad/server/token.key) \
              /var/www/jobs/upolujksiazke/jobs/site.hcl
